# Generated by Django 5.1.3 on 2024-11-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physician', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('home_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('preferred_contact_method', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Mail', 'Mail')], max_length=20)),
                ('referring_provider', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('insurance_company', models.CharField(max_length=200)),
                ('insurance_member_id', models.CharField(max_length=200)),
                ('effective_date_of_insurance', models.DateField(blank=True)),
                ('secondary_insurance_company', models.CharField(blank=True, max_length=200)),
                ('secondary_insurance_member_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('web_upload_status', models.CharField(choices=[('Need to Upload', 'Need to Upload'), ('Uploaded', 'Uploaded')], default='Need to Upload', max_length=100)),
                ('medical_record_number', models.CharField(blank=True, max_length=20)),
                ('eligibility_status', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
