# Generated by Django 5.1.3 on 2024-11-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='effective_date_of_insurance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='eligibility_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='home_phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_member_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_record_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='physician',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preferred_contact_method',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='referring_provider',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='secondary_insurance_company',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='secondary_insurance_member_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='web_upload_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='zip_code',
        ),
    ]
