# Generated by Django 5.1.3 on 2024-11-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patientt_delete_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patientt',
            new_name='Patient',
        ),
    ]
